#!/bin/bash
apt-get update  && apt-get upgrade
apt install xorg lightdm i3 polybar 
echo "first step DOOIT!!!!"
apt install feh compton unzip xpdf git ccrypt nemo python3-pip ffmpeg 
pip3 install youtube-dl
echo "2do step ready"
echo "loading config files"
git clone https://github.com/ducl1296/Debian-minimal-install-wmi3.git
cd Desbian-minimal-install-wmi3
cp /fonts/* ~/.local/share/fonts

