#!/bin/bash
user=$USER
echo "deb http://ftp.debian.org/debian buster-backports main" | sudo -A tee /etc/apt/sources.list.d/backports.list
sudo -A apt-get update
sudo -A apt-get upgrade
sudo -A apt install xorg slim i3 terminator mousepad plymouth -y
echo "first step DOOIT!!!!"
sudo -A apt install feh compton unzip xpdf git ccrypt nemo python3-pip ffmpeg lxappearance pulseaudio pavucontrol mpd ncmpcpp -y
sudo -A apt install cmake cmake-data libcairo2-dev libxcb1-dev libxcb-ewmh-dev libxcb-icccm4-dev libxcb-image0-dev libxcb-randr0-dev libxcb-util0-dev libxcb-xkb-dev pkg-config python-xcbgen xcb-proto libxcb-xrm-dev i3-wm libasound2-dev libmpdclient-dev libiw-dev libcurl4-openssl-dev libpulse-dev -y
sudo -A pip3 install youtube-dl
echo "2do step ready"
echo "loading config files"
git clone https://github.com/ducl1296/Debian-minimal-install-wmi3.git
sudo apt -t buster-backports install polybar -y
cd Desbian-minimal-install-wmi3
sudo -A mkdir /usr/share/slim/themes
sudo -A cp -r config/slim/darky_pink /usr/share/slim/themes/
sudo -A cp config/slim/slim.conf /etc/slim.conf
mkdir /home/$user/.local/share/fonts
cp fonts/* /home/$user/.local/share/fonts
echo "fonts copiadas"
mkdir /home/$user/.config/wallpapers
cp wallpapers/* /home/$user/.config/wallpapers/
echo "wallpapers copiados"
mkdir /home/$user/.config/scripts
cp scripts/* /home/$user/.config/scripts/
echo "scripts copiados"
cp -r config/* /home/$user/.config/
echo "configuraciones copiadas"
####################################MPD CONFIG###############################################################
sudo -A mkdir /home/"$USER"/música
sudo -A touch /var/lib/mpd/db
sudo -A touch /var/lib/mpd/mpdstate
sudo -A touch /var/run/mpd/mpd.pid
sudo -A touch /var/log/mpd/mpd.log
sudo -A touch /var/log/mpd/mpd.error
sudo -A cp config/mpd/mpd.conf /etc/mpd.conf
####################################INSTALL PLYMOUTH#########################################################
sudo -A echo "GRUB_GFXMODE=1980x1080" >> /etc/default/grub
sudo -A echo "GRUB_CMDLINE_LINUX_DEFAULT=/"quiet splash/"" >> /etc/default/grub
sudo -A update-grub2
sudo -A /usr/share/plymouth/themes/circle
sudo -A cp -r config/plymouth/theme/* /usr/share/plymouth/themes/circle/
sudo -A plymouth-set-default-theme -R circle
#############################################################################################################
echo "aqui vamos"
sleep 5
systemctl reboot
